server:
  port: 9080
spring:
  application:
    name: scyp-console-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    host: smtp.exmail.qq.com
    username: service@cypfintech.com
    password: YbFNjvoyAsA9gP32
    protocol: smtp
    properties:  ##启用加密协议
      mail:
        smtp:
          auto: true
          ssl:
            enable: true
      recipients: huajun.zhang@cypfintech.com
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8081/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
management:
  security:
    enabled: false
mymonitor:
#  health:
  model: redis,db,configServer,hystrix,discoveryComposite,discoveryComposite.discoveryClient,discoveryComposite.eureka,kafkaConsumer,kafkaProductor
  registNotify: false
  refreshServiceSeconds: 60000
  compareAllServiceSeconds: 90000
  healthNotifyModel: all
#配置登录用户密码
security:
  user:
    name: admin
    password: admin
CloudConsolePlugins:
  pluginType[0]:
    plugin: Kafka
    url: 127.0.0.1:9092
    menuname: kafka监控
    pluginSubMenus[0]:
      id: Brokers
      submenuname: Brokers
      submenuaddress: /kafkaClient/listBrokers
    pluginSubMenus[1]:
      id: Topics
      submenuname: Topics
      submenuaddress: /kafkaClient/listTopics
    pluginSubMenus[2]:
      id: Consumers
      submenuname: Consumers
      submenuaddress: /kafkaClient/listConsumers
  pluginType[1]:
    plugin: ZooKeeper
    url: 127.0.0.1:2183
    menuname: ZooKeeper监控
    menuaddress: /zkClient/listNodes
  pluginType[2]:
    plugin: Redis
    url: 127.0.0.1:6379
    password:
    menuname: Redis监控
    menuaddress: /redisClient/listRedis
  pluginType[3]:
    plugin: MySql
    url: jdbc:mysql://192.168.6.253:3306/scyp-system?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver: com.mysql.jdbc.Driver
    username: scyp
    password: Ceying2019
    menuname: MySql监控
    menuaddress: /mySqlClient/listMySql
jobScheduler:
  jobFilePath: "C:\\scyp\\jobScheduler.json"